import { palette } from "@/constants/colors";
import { useSafeBack } from "@/hooks/useSafeBack";
import { AlertTriangle, ArrowLeft } from "lucide-react-native";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const STATEMENTS: string[] = [
  "EAGOH provides informational and entertainment content only.",
  "EAGOH does not guarantee predictions, outcomes, rankings, or analysis accuracy.",
  "Users should independently verify important information before relying on it.",
];

const DISCLAIMER_SECTIONS: { title: string; body: string }[] = [
  {
    title: "Not Financial Advice",
    body: "EAGOH is not a financial advisor, investment platform, or trading tool. Any predictions, analyses, or insights generated by the platform are for entertainment and informational purposes only. Do not make financial decisions based solely on EAGOH output. Consult a qualified financial professional for investment advice.",
  },
  {
    title: "Not Medical Advice",
    body: "EAGOH is not a medical professional. The platform does not provide medical diagnoses, treatment recommendations, or health advice. Always consult a licensed healthcare provider for medical concerns.",
  },
  {
    title: "Not Legal Advice",
    body: "EAGOH does not provide legal counsel. No content on this platform should be interpreted as legal advice. Consult a qualified attorney for legal matters.",
  },
  {
    title: "AI Accuracy",
    body: "EAGOH uses artificial intelligence models that may produce inaccurate, incomplete, or inconsistent results. AI-generated content should not be treated as factual without independent verification. The platform makes no warranty regarding the accuracy, reliability, or completeness of AI-generated outputs.",
  },
  {
    title: "Neurons",
    body: "Neurons are virtual platform currency with no real-world monetary value. They cannot be exchanged for cash, transferred outside the EAGOH platform, or used as any form of financial instrument.",
  },
  {
    title: "No Gambling",
    body: "EAGOH is not a gambling platform. No feature within EAGOH constitutes betting, wagering, or gambling of any kind. Neurons are not stakes and cannot be won or lost in games of chance.",
  },
  {
    title: "Third-Party Content",
    body: "EAGOH may display content from third-party AI providers, marketplace vendors, and faction members. We do not endorse, verify, or assume responsibility for third-party content accuracy.",
  },
  {
    title: "Platform Availability",
    body: "EAGOH strives to maintain continuous platform availability but does not guarantee uninterrupted service. Maintenance, updates, or unforeseen technical issues may result in temporary downtime.",
  },
];

export default function DisclaimerScreen(): JSX.Element {
  const safeBack = useSafeBack();

  return (
    <SafeAreaView edges={["top"]} style={styles.safe}>
      <View style={styles.header}>
        <Pressable
          onPress={() => { safeBack(); }}
          style={({ pressed }) => [styles.backBtn, pressed && { opacity: 0.6 }]}
        >
          <ArrowLeft color={palette.text} size={20} />
        </Pressable>
        <AlertTriangle color={palette.ember} size={20} />
        <Text style={styles.headerTitle}>Disclaimer</Text>
      </View>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Core statements */}
        <View style={styles.coreBox}>
          {STATEMENTS.map((stmt, i) => (
            <View key={i} style={styles.coreRow}>
              <View style={styles.coreDot} />
              <Text style={styles.coreText}>{stmt}</Text>
            </View>
          ))}
        </View>

        {/* Detailed sections */}
        {DISCLAIMER_SECTIONS.map((section) => (
          <View key={section.title} style={styles.section}>
            <Text style={styles.sectionTitle}>{section.title}</Text>
            <Text style={styles.sectionBody}>{section.body}</Text>
          </View>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.void },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    backgroundColor: palette.obsidian,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: palette.line,
  },
  headerTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "900",
    flex: 1,
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 18, paddingBottom: 60 },
  coreBox: {
    padding: 16,
    borderRadius: 5,
    backgroundColor: "rgba(255,77,109,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,77,109,0.24)",
    marginBottom: 22,
    gap: 12,
  },
  coreRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  coreDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: palette.ember,
    marginTop: 7,
  },
  coreText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 20,
    flex: 1,
  },
  section: {
    marginBottom: 22,
    padding: 14,
    borderRadius: 5,
    backgroundColor: palette.panel,
    borderWidth: 1,
    borderColor: palette.line,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 8,
  },
  sectionBody: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "500",
  },
});
